title: FS24
description: Bem-vindo à Formação Desenvolvedor Fullstack da Digital College! Este repositório contém todos os recursos e materiais necessários para o curso. Leia atentamente as seções abaixo para entender como este repositório funciona e quais padrões adotamos.
theme: jekyll-theme-cayman

show_downloads: true
